version: "3.3"

volumes:
  app_db_data:


services:
  app:
    image: '${DOCKER_IMAGE_APP}:latest'
    container_name: app
    env_file:
      - docker_dev.env
    build:
      context: ../../
      dockerfile: infra/docker/app.dockerfile
    ports:
      - "80:80"
      - "8888:8888"
    volumes:
      - ../../app:/code/app
    networks:
      - "{{cookiecutter.project}}-network"

  db:
    image: postgres:14-alpine
    volumes:
      - app_db_data:/var/lib/postgresql/data/pgdata
    env_file:
      - docker_dev.env
    ports:
      - "5432:5432"
    networks:
      - "{{cookiecutter.project}}-network"

networks:
  "{{cookiecutter.project}}-network":
    driver: bridge
